@startuml
skinparam classAttributeIconSize 0
title US213-CD

class ScheduledFlightController {
    + getFlightsByAircraft(registrationNumber: String): ResponseEntity<CollectionModel<EntityModel<ScheduledFlightViewDTO>>>
}

class ScheduledFlightService {
    + getScheduledFlightsByAircraft(registrationNumber: String): List<ScheduledFlightViewDTO>
}

interface ScheduledFlightRepository <<Repository>> {
    + findByAircraft_RegistrationNumber(registrationNumber: RegistrationNumber): List<ScheduledFlight>
}

class ScheduledFlight <<Entity>> <<Root>> {
    - scheduledDateTime: LocalDateTime
    - status: FlightStatus
    + getRoute(): Route
    + getAircraft(): Aircraft
}

class Route <<Entity>> {
    + getRouteId(): RouteId
}

class RegistrationNumber <<Value Object>> {
    - number: String
}

class RouteId <<Value Object>> {
    - id: String
}

class ScheduledFlightViewDTO <<Record>> {
    + id: Long
    + routeId: String
    + registrationNumber: String
    + scheduledDateTime: String
    + status: String
}

ScheduledFlightController ..> ScheduledFlightViewDTO : produces >
ScheduledFlightController --> ScheduledFlightService : uses >

ScheduledFlightService ..> ScheduledFlightViewDTO : creates >
ScheduledFlightService ..> RegistrationNumber : creates >
ScheduledFlightService --> ScheduledFlightRepository : uses >

ScheduledFlightRepository --> ScheduledFlight : reads >
ScheduledFlightService --> ScheduledFlight : reads >
ScheduledFlightService --> Route : reads >
@enduml