@startuml
title US213-SSD
autonumber
actor "ATCC" as Operator
participant "System" as Sys

activate Operator
Operator -> Sys : GET /api/scheduled-flights/aircraft/{registrationNumber}
activate Sys
Sys --> Operator : Returns the scheduled flights for the aircraft (200 OK)
deactivate Sys
deactivate Operator
@enduml