@startuml
title US219-SD
autonumber
actor "Maintenance Supervisor" as Supervisor
participant ":MaintenanceController" as Ctrl
participant ":MaintenanceService" as Service
participant ":MaintenanceRecordRepository" as Repo

activate Supervisor
Supervisor -> Ctrl : GET /api/maintenance/records/ongoing
activate Ctrl

Ctrl -> Service : getOngoingMaintenances()
activate Service

Service -> Repo : findByStatus(MaintenanceRecordStatus.SCHEDULED)
activate Repo
Repo --> Service : List<MaintenanceRecord>
deactivate Repo

Service --> Ctrl : List<MaintenanceRecord>
deactivate Service

loop for each MaintenanceRecord
    Ctrl -> Ctrl : create EntityModel(record)
    Ctrl -> Ctrl : add link ("complete-this-record")
end

Ctrl --> Supervisor : 200 OK\n(CollectionModel<EntityModel<MaintenanceRecord>>)
deactivate Ctrl
deactivate Supervisor
@enduml