@startuml
skinparam style strictuml
autonumber
title SSD-US102

actor "ATCC" as ATCC
participant "AISafe System" as SYS

ATCC -> SYS : POST /api/aircraft-models/instances (registrationNumber, modelName, manufacturingDate, seatingCapacity)
activate SYS

SYS --> ATCC : 201 Created (Aircraft Details + HATEOAS Links)
deactivate SYS

@enduml