@startuml
skinparam style strictuml
hide empty members
title DM-US102

package "Aircraft Aggregate" {

    class Aircraft <<Entity>> <<Root>> {
        - version : Long
        - manufacturingDate : LocalDate
        - actualSeatingCapacity : Integer
        - totalFlightHours : Double
    }

    class RegistrationNumber <<Value Object>> {
        - number : String
    }

    enum AircraftStatus <<Enum>> {
         ACTIVE
         INACTIVE
         UNDER_MAINTENANCE
    }
}

package "Aircraft Model Aggregate" {
    class AircraftModel <<Entity>> <<Root>>
}

Aircraft *-- "1" RegistrationNumber : identified by >
Aircraft *-- "1" AircraftStatus : initialized as >
Aircraft "*" --> "1" AircraftModel : is instance of >

@enduml