@startuml
autonumber
title US202-SD

actor "Backoffice Operator" as Operator
participant ":AircraftModelController" as Ctrl
participant ":AircraftModelService" as Service
participant ":AircraftModelRepository" as Repo
participant "model\n:AircraftModel" as Entity

activate Operator
Operator -> Ctrl : PATCH /api/aircraft-models/models/{modelName}/image\n(MultipartFile file)
activate Ctrl

Ctrl -> Service : updateModelImage(modelName, file)
activate Service

Service -> Repo : findByModelName(new ModelName(modelName))
activate Repo
Repo --> Service : Optional<AircraftModel>
deactivate Repo

Service -> Service : saveImageLocally(file)
activate Service
Service --> Service : savedImagePath
deactivate Service

Service -> Entity : updateImage(savedImagePath)
activate Entity
Entity --> Service : success
deactivate Entity

Service -> Repo : save(model)
activate Repo
Repo --> Service : savedModel
deactivate Repo

Service --> Ctrl : AircraftModelViewDTO
deactivate Service

Ctrl --> Operator : 200 OK (AircraftModelViewDTO)
deactivate Ctrl
deactivate Operator
@enduml