@startuml
skinparam classAttributeIconSize 0
hide empty members
title US218-DM

package "Maintenance Record Aggregate" {
    class MaintenanceRecord <<Entity>> <<Root>> {
        - description: String
        - startDate: LocalDateTime
        - expectedDuration: Integer
        - cost: Double
    }

    enum ComponentCategory <<Enumeration>> {
        ENGINE
        AIRFRAME
        AVIONICS
        INTERIOR
        EXTERIOR
    }

    enum MaintenanceRecordStatus <<Enumeration>> {
        SCHEDULED
        COMPLETED
    }

    MaintenanceRecord "1" --> "1" ComponentCategory : categorized under >
    MaintenanceRecord "1" --> "1" MaintenanceRecordStatus : has >
}

package "Aircraft Aggregate" {
    class Aircraft <<Entity>> <<Root>> {
    }

    class RegistrationNumber <<Value Object>> {
        - number: String
    }

    Aircraft "1" *-- "1" RegistrationNumber : identified by >
}

MaintenanceRecord "*" --> "1" Aircraft : performed on >
@enduml