@startuml
skinparam style strictuml
hide empty members
title DM-US106

package "Airport Aggregate" {

    class Airport <<Entity>> <<Root>> {
        - version : Long
        - name : String
        - city : String
        - country : String
        - timezone : String
    }

    class IATACode <<Value Object>> {
        - code : String
    }

    class Coordinates <<Value Object>> {
        - latitude : Double
        - longitude : Double
    }

    enum AirportType <<Enum>> {
        INTERNATIONAL
        REGIONAL
        DOMESTIC
    }

    enum AirportStatus <<Enum>> {
        OPERATIONAL
        CLOSED
        UNDER_MAINTENANCE
    }

    class Runway <<Entity>> {
        - name : String
        - length : Double
        - orientation : String
    }

    Airport *-- "1" IATACode : identified by >
    Airport *-- "1" Coordinates : located at >
    Airport *-- "1" AirportType : is of type >
    Airport *-- "1" AirportStatus : initialized as >
    Airport *-- "0..*" Runway : contains >
}
@enduml