@startuml
title US227-SSD
autonumber

actor "ATCC" as Operator
participant "AISafe System" as System

activate Operator
Operator -> System : GET /api/aircraft-models/fuel-efficiency?regNum={registrationNumber}
activate System
System --> Operator : 200 OK (FuelEfficiencyDTO)
deactivate System
deactivate Operator
@enduml