@startuml
title US209 - SD
autonumber
actor "ATCC" as Operator
participant ":RouteController" as Ctrl
participant ":RouteService" as Service
participant ":RouteRepository" as Repo
participant "page\n:Page<Route>" as PageRoute

activate Operator
Operator -> Ctrl : GET /api/routes/involving/{iataCode}?page=0&size=10
activate Ctrl

Ctrl -> Service : getRoutesByAirport(iataCode, pageable)
activate Service

Service -> Repo : findRoutesByAirport(iataCode.toUpperCase(), pageable)
activate Repo
Repo --> Service : Page<Route>
deactivate Repo

Service -> PageRoute : map(this::convertToDTO)
activate PageRoute
PageRoute --> Service : Page<RouteViewDTO>
deactivate PageRoute

Service --> Ctrl : Page<RouteViewDTO>
deactivate Service

Ctrl -> Ctrl : assemble PagedModel (using PagedResourcesAssembler\nand this::addLinksToRoute)
Ctrl --> Operator : 200 OK (PagedModel<EntityModel<RouteViewDTO>>)
deactivate Ctrl
deactivate Operator
@enduml