@startuml
title US207-SD
autonumber
actor "Backoffice Operator" as Operator
participant ":AirportController" as Ctrl
participant ":AirportService" as Service
participant "file\n:MultipartFile" as File
participant ":AirportRepository" as Repo
participant "airport\n:Airport" as Entity

activate Operator
Operator -> Ctrl : PATCH /api/airports/{iataCode}/image\n(file)
activate Ctrl

Ctrl -> Service : updateAirportImage(iataCode, file)
activate Service

Service -> Repo : findByIataCodeString(iataCode)
activate Repo
Repo --> Service : Optional<Airport>
deactivate Repo

Service -> File : transferTo(filePath)
activate File
File --> Service : success
deactivate File

Service -> Entity : updateImage(fileUrl)
activate Entity
Entity --> Service : success
deactivate Entity

Service -> Repo : save(airport)
activate Repo
Repo --> Service : savedAirport
deactivate Repo

Service -> Service : create AirportViewDTO
Service --> Ctrl : AirportViewDTO
deactivate Service

Ctrl -> Ctrl : wrap in EntityModel & add HATEOAS self link
Ctrl --> Operator : 200 OK (EntityModel<AirportViewDTO>)
deactivate Ctrl
deactivate Operator
@enduml