@startuml
title US211 - SSD
autonumber
actor "ATCC" as Operator
participant "System" as Sys

activate Operator
Operator -> Sys : Requests to view airports grouped by a specific criteria (by = "region", "country" or "both")
activate Sys
Sys --> Operator : Returns the grouped airports structure (200 OK)
deactivate Sys
deactivate Operator
@enduml