@startuml
title US211 - CD
skinparam classAttributeIconSize 0

class AirportController {
    + getAirportsGrouped(by: String): ResponseEntity<Object>
}

class AirportService {
    + getAirportsGrouped(groupBy: String): Object
    - extractRegion(dto: AirportViewDTO): String
    - mapToDTO(airport: Airport): AirportViewDTO
}

interface AirportRepository <<Repository>> {
    + findAll(): List<Airport>
}

class Airport <<Entity>> <<Root>> {
    - country: String
    - timezone: String
    + getCountry(): String
    + getTimezone(): String
}

class AirportViewDTO <<DTO>> {
    + iataCode: String
    + country: String
    + timezone: String
}

AirportController ..> AirportViewDTO : produces >
AirportController --> AirportService : uses >

AirportService ..> AirportViewDTO : creates >
AirportService --> AirportRepository : uses >

AirportRepository --> Airport : queries >
@enduml