@startuml
skinparam style strictuml
autonumber
actor "ATCC/Backoffice" as User
participant "AISafe API" as Sys

title SSD - US112

User -> Sys : PATCH /api/routes/{id} (UpdateRouteDTO)
activate Sys
Sys --> User : 200 OK (RouteViewDTO + Links HATEOAS)
deactivate Sys
@enduml