@startuml
title US206-SSD
autonumber
actor "ATCC" as Operator
participant "System" as Sys

activate Operator
Operator -> Sys : Requests the total operational hours for each aircraft in the fleet (pageable parameters)
activate Sys
Sys --> Operator : Returns a paginated list of aircraft with their operational hours (200 OK)
deactivate Sys
deactivate Operator
@enduml