@startuml
skinparam style strictuml
skinparam packageStyle rectangle
title CD-US103

package "API Layer" {
    class AircraftController {
        + getAircraft(registrationNumber: String): ResponseEntity<EntityModel<AircraftViewDTO>>
    }
}

package "Application Layer" {
    class AircraftService {
        + getAircraftByRegistrationNumber(regNum: String): AircraftViewDTO
    }
    class AircraftViewDTO <<DTO>> {
        + registrationNumber: String
        + modelName: String
        + manufacturingDate: LocalDate
        + seatingCapacity: Integer
        + status: String
        + modelPhotoUrl: String
    }
}

package "Domain Layer" {
    class Aircraft <<Entity>> <<Root>> {
        - pk: Long
        - version: Long
        - manufacturingDate: LocalDate
        - actualSeatingCapacity: Integer
        - totalFlightHours: Double
        + getRegistrationNumber(): RegistrationNumber
        + getAircraftModel(): AircraftModel
        + getStatus(): AircraftStatus
        + getManufacturingDate(): LocalDate
        + getActualSeatingCapacity(): Integer
    }
    class RegistrationNumber <<Value Object>> {
        - number: String
    }
}

package "Infrastructure Layer" {
    interface AircraftRepository <<Repository>> {
        + findByRegistrationNumber(registrationNumber: RegistrationNumber): Optional<Aircraft>
    }
}

AircraftController .down.> AircraftViewDTO : uses
AircraftController .down.> AircraftService : calls
AircraftService .down.> AircraftViewDTO : creates
AircraftService .down.> RegistrationNumber : creates
AircraftService .down.> AircraftRepository : uses
AircraftService .down.> Aircraft : reads

Aircraft *-- "1" RegistrationNumber
@enduml