@startuml
title US214-SD
autonumber
actor "ATCC" as Operator
participant ":RouteController" as Ctrl
participant ":RouteService" as Service
participant ":RouteRepository" as Repo

activate Operator
Operator -> Ctrl : GET /api/routes/active/sorted?sortBy={sortBy}&page={page}&size={size}
activate Ctrl

Ctrl -> Service : getActiveRoutesSorted(sortBy, pageable)
activate Service

alt sortBy == "popularity"
    Service -> Repo : findAllActiveRoutesSortedByPopularity(pageable)
    activate Repo
    Repo --> Service : Page<Route>
    deactivate Repo
else sortBy != "popularity"
    Service -> Repo : findAllActiveRoutesSortedByDistance(pageable)
    activate Repo
    Repo --> Service : Page<Route>
    deactivate Repo
end

Service --> Ctrl : Page<RouteViewDTO>
deactivate Service

Ctrl --> Operator : 200 OK\n(PagedModel<EntityModel<RouteViewDTO>>)
deactivate Ctrl
deactivate Operator
@enduml