@startuml
skinparam classAttributeIconSize 0
title US214-CD

class RouteController {
    + getActiveRoutesSorted(sortBy: String, pageable: Pageable, assembler: PagedResourcesAssembler<RouteViewDTO>): ResponseEntity<PagedModel<EntityModel<RouteViewDTO>>>
    - addLinksToRoute(route: RouteViewDTO): EntityModel<RouteViewDTO>
}

class RouteService {
    + getActiveRoutesSorted(sortBy: String, pageable: Pageable): Page<RouteViewDTO>
    - convertToDTO(route: Route): RouteViewDTO
}

interface RouteRepository <<Repository>> {
    + findAllActiveRoutesSortedByPopularity(pageable: Pageable): Page<Route>
    + findAllActiveRoutesSortedByDistance(pageable: Pageable): Page<Route>
}

class Route <<Entity>> <<Root>> {
    - minimumCapacity: Integer
    + getRouteId(): RouteId
    + getOrigin(): Airport
    + getDestination(): Airport
    + getStatus(): RouteStatus
    + getMinimumCapacity(): Integer
}

class Airport <<Entity>> {
    + getIataCode(): IATACode
}

class IATACode <<Value Object>> {
    - code: String
}

class RouteId <<Value Object>> {
    - id: String
}

enum RouteStatus <<Enumeration>> {
    ACTIVE
    INACTIVE
}

class RouteViewDTO <<Record>> {
    + routeId: String
    + originIata: String
    + destinationIata: String
    + status: String
    + minimumCapacity: Integer
}

RouteController ..> RouteViewDTO : produces >
RouteController --> RouteService : uses >

RouteService ..> RouteViewDTO : creates >
RouteService --> RouteRepository : uses >
RouteService --> Route : reads >
RouteService --> Airport : reads >
RouteService --> IATACode : reads >

RouteRepository --> Route : reads >
Route --> RouteStatus : uses >
Route --> RouteId : uses >
@enduml