@startuml
skinparam style strictuml
skinparam packageStyle rectangle
hide empty members
title DM-US108

package "Airport Aggregate" {
    class Airport <<Entity>> <<Root>> {
        - version : Long
        - iataCode : IATACode
        - name : String
        - city : String
        - country : String
        - type : AirportType
        - status : AirportStatus
    }
}
@enduml