@startuml
skinparam style strictuml
autonumber
actor "ATCC" as ATCC
participant "AISafe API" as SYS

title SSD - US111

ATCC -> SYS : GET /api/routes/{id}/history
activate SYS

SYS --> ATCC : 200 OK (CollectionModel<RouteHistoryDTO> + Links HATEOAS)
deactivate SYS

@enduml